from yacs.config import CfgNode as CN

CFG = CN()

CFG.RUN_NAME = 'freematch_cifar10_40'
CFG.OUTPUT_DIR = './model_ckpt'
CFG.CONT_TRAIN = False
CFG.RESUME = ''
CFG.SEED = -1
CFG.LOG_DIR = './logs'
CFG.USE_CUDA = True
CFG.VALIDATE_ONLY = False
CFG.ALGORITHM = 'freematch'

CFG.USE_TB = True
CFG.TB_DIR = 'tensorboard_runs/cifar_10_40_run_0'

CFG.X_SHARP = False
CFG.RHO = 0.05

CFG.NCSAM = CN()
CFG.NCSAM.ENABLED = False
CFG.NCSAM.START_ITER = 0
CFG.NCSAM.WARMUP_ITERS = 0
CFG.NCSAM.RAMP_ITERS = 2048
CFG.NCSAM.PLATEAU_ITERS = 8192
CFG.NCSAM.DECAY_ITERS = 8192
CFG.NCSAM.MIN_LAMBDA = 0.05
CFG.NCSAM.MAX_LAMBDA = 0.5
CFG.NCSAM.MIN_SELECT_RATIO = 0.1
CFG.NCSAM.SELECT_RATIO = 0.5
CFG.NCSAM.MARGIN_TEMPERATURE = 1.0
CFG.NCSAM.DENSITY_POWER = 1.0
CFG.NCSAM.MIN_DENSITY = 0.05
CFG.NCSAM.SINGLETON_DENSITY = 0.5
CFG.NCSAM.BATCH_PRIOR_WEIGHT = 0.5
CFG.NCSAM.CLASS_BALANCE_POWER = 1.0
CFG.NCSAM.MAX_BALANCE_WEIGHT = 5.0
CFG.NCSAM.MAX_SAMPLE_WEIGHT = 10.0

CFG.DATASET = CN()
CFG.DATASET.PREPARE = True
CFG.DATASET.DIR = './data_download'
CFG.DATASET.NAME = 'cifar10'
CFG.DATASET.NUM_LABELED = 250
CFG.DATASET.NUM_CLASSES = 10
CFG.DATASET.NUM_WORKERS = 4
CFG.DATASET.CONVERT_ONE_HOT = True
CFG.DATASET.IMG_SIZE = 32
CFG.DATASET.URATIO = 7
CFG.DATASET.TRAIN_BATCH_SIZE = 64
CFG.DATASET.TEST_BATCH_SIZE = 256
CFG.DATASET.CROP_RATIO = 0.875
CFG.DATASET.PIXEL_MEAN = [0.485, 0.456, 0.406]
CFG.DATASET.PIXEL_STD = [0.229, 0.224, 0.225]
CFG.DATASET.RANDAUG_N = 3

CFG.MODEL = CN()
CFG.MODEL.NAME = 'wrn_28_2'
CFG.MODEL.PRETRAINED = False
CFG.MODEL.PRETRAINED_PATH = ''

CFG.OPTIMIZER = CN()
CFG.OPTIMIZER.NAME = 'SGD'
CFG.OPTIMIZER.LR = 0.03
CFG.OPTIMIZER.MOMENTUM = 0.9
CFG.OPTIMIZER.NESTEROV = True
CFG.OPTIMIZER.WEIGHT_DECAY = 0.0005
CFG.OPTIMIZER.SKIP_BN = True

CFG.TRAINER = CN()
CFG.TRAINER.SAT_EMA = 0.999
CFG.TRAINER.AMP_ENABLED = False
CFG.TRAINER.NUM_WARMUP_ITERS = 0
CFG.TRAINER.NUM_TRAIN_ITERS = 1048576 # 2^20
CFG.TRAINER.NUM_EVAL_ITERS = 5120
CFG.TRAINER.NUM_LOG_ITERS = 512
CFG.TRAINER.EMA_VAL = 0.999
CFG.TRAINER.ULB_LOSS_RATIO = 1.0
CFG.TRAINER.ENT_LOSS_RATIO = 0.1
